application: xp1r4t3proxy
version: securable1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /static
  static_dir: static
  secure: optional

- url: /.*
  script: mirror.app
  secure: optional